title: Scientifika
author: Ricardo Arcila
email: dana@scientifika.eu
description: > # this means to ignore newlines until "baseurl:"
  We help researchers organise scientific events

twitter_username: Scientifika1
github_username:  macrod68

baseurl: ""

collections:
  pages:
    output: true
    permalink: /:path
  mainpages:
    output: true
    permalink: /:path

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package.json
  - Gruntfile.js
  - node_modules
  - index.js

sass:
    style: compressed    