title: Scientifika
author: Ricardo Arcila
email: dana@scientifika.eu
description: > # this means to ignore newlines until "baseurl:"
  We help researchers organise scientific events

twitter_username: Scientifika_eu
github_username: 

baseurl: ""

google_analytics: UA-132832693-1

collections:
  pages:
    output: true
    permalink: /:path
  mainpages:
    output: true
    permalink: /:path
  events:
    output: true
    permalink: /:path
  testimonials:
    output: true
    permalink: /:path

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package.json
  - Gruntfile.js
  - node_modules
  - index.js
  - src
  - public

sass:
    style: compressed
